const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "256749388682";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "2814-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "2814",
  ownername:process.env.OWNER_NAME|| "2814",

  sessionName:process.env.SESSION_ID || "SUHAIL_06_27_01_31_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjA4LFxuICAgICAgICAxMTgsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTQzLFxuICAgICAgICA0MSxcbiAgICAgICAgMTQ0LFxuICAgICAgICAyMTksXG4gICAgICAgIDE1NixcbiAgICAgICAgNDYsXG4gICAgICAgIDAsXG4gICAgICAgIDIzNixcbiAgICAgICAgNzYsXG4gICAgICAgIDU3LFxuICAgICAgICAxODEsXG4gICAgICAgIDM1LFxuICAgICAgICAxNTUsXG4gICAgICAgIDAsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMTU3LFxuICAgICAgICA2NyxcbiAgICAgICAgMTM0LFxuICAgICAgICAxMDksXG4gICAgICAgIDEyOSxcbiAgICAgICAgNTAsXG4gICAgICAgIDM3LFxuICAgICAgICAyMjQsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTAzLFxuICAgICAgICAxNzAsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMjUzLFxuICAgICAgICA4MlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA3OCxcbiAgICAgICAgMjgsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTcsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTkzLFxuICAgICAgICA0NCxcbiAgICAgICAgOTEsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMjI4LFxuICAgICAgICAxNTcsXG4gICAgICAgIDM4LFxuICAgICAgICAyNTQsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTI0LFxuICAgICAgICA2NyxcbiAgICAgICAgMTU3LFxuICAgICAgICAxMSxcbiAgICAgICAgMTgsXG4gICAgICAgIDE1NixcbiAgICAgICAgMTUwLFxuICAgICAgICA1NixcbiAgICAgICAgNDIsXG4gICAgICAgIDg1LFxuICAgICAgICAxOSxcbiAgICAgICAgMCxcbiAgICAgICAgNTAsXG4gICAgICAgIDE5NixcbiAgICAgICAgMjEwLFxuICAgICAgICAxMzksXG4gICAgICAgIDE3NSxcbiAgICAgICAgNzVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQ4LFxuICAgICAgICAyMDEsXG4gICAgICAgIDE1MSxcbiAgICAgICAgNzAsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMjQzLFxuICAgICAgICAxOTcsXG4gICAgICAgIDIyMSxcbiAgICAgICAgNTgsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMzcsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMjMzLFxuICAgICAgICA1MixcbiAgICAgICAgMTM1LFxuICAgICAgICA3MCxcbiAgICAgICAgMTYyLFxuICAgICAgICAxNDYsXG4gICAgICAgIDQ1LFxuICAgICAgICAxOTEsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTcsXG4gICAgICAgIDExNSxcbiAgICAgICAgMTg2LFxuICAgICAgICAxOTQsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTU3LFxuICAgICAgICAyMzIsXG4gICAgICAgIDg4LFxuICAgICAgICAxMDMsXG4gICAgICAgIDY4LFxuICAgICAgICAxMDZcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTIyLFxuICAgICAgICAzOCxcbiAgICAgICAgMjM3LFxuICAgICAgICAyMzMsXG4gICAgICAgIDI1MixcbiAgICAgICAgMjksXG4gICAgICAgIDE4OSxcbiAgICAgICAgNzQsXG4gICAgICAgIDUyLFxuICAgICAgICAxODUsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMjAzLFxuICAgICAgICAxNzksXG4gICAgICAgIDg3LFxuICAgICAgICAxODAsXG4gICAgICAgIDc5LFxuICAgICAgICAxNDksXG4gICAgICAgIDE5MSxcbiAgICAgICAgMCxcbiAgICAgICAgMjI3LFxuICAgICAgICAyMjUsXG4gICAgICAgIDIsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTMyLFxuICAgICAgICA4NixcbiAgICAgICAgMTI0LFxuICAgICAgICAxMTUsXG4gICAgICAgIDc3LFxuICAgICAgICAyNDQsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTkwLFxuICAgICAgICA0M1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTEyLFxuICAgICAgICAxNTMsXG4gICAgICAgIDMzLFxuICAgICAgICAxOTQsXG4gICAgICAgIDExMyxcbiAgICAgICAgMTA3LFxuICAgICAgICAxODAsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTA3LFxuICAgICAgICAzOCxcbiAgICAgICAgMTk2LFxuICAgICAgICAyMDMsXG4gICAgICAgIDE5LFxuICAgICAgICA5NixcbiAgICAgICAgNDEsXG4gICAgICAgIDk5LFxuICAgICAgICA5OCxcbiAgICAgICAgMjAzLFxuICAgICAgICAxNjAsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMTA0LFxuICAgICAgICAyNDYsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMjMyLFxuICAgICAgICA1NCxcbiAgICAgICAgMTk5LFxuICAgICAgICAyNTMsXG4gICAgICAgIDgsXG4gICAgICAgIDk1LFxuICAgICAgICAxNTksXG4gICAgICAgIDQ3LFxuICAgICAgICA2OFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4OSxcbiAgICAgICAgNzksXG4gICAgICAgIDIwNSxcbiAgICAgICAgMjMsXG4gICAgICAgIDE2MixcbiAgICAgICAgMTkwLFxuICAgICAgICAxMzcsXG4gICAgICAgIDgyLFxuICAgICAgICAxODksXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTYyLFxuICAgICAgICAxNjIsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMjA3LFxuICAgICAgICAxNDMsXG4gICAgICAgIDk4LFxuICAgICAgICAyMixcbiAgICAgICAgMzQsXG4gICAgICAgIDE0MSxcbiAgICAgICAgMjMyLFxuICAgICAgICA1MixcbiAgICAgICAgNzIsXG4gICAgICAgIDE2NixcbiAgICAgICAgNjcsXG4gICAgICAgIDY0LFxuICAgICAgICAzNyxcbiAgICAgICAgMjEwLFxuICAgICAgICAyMSxcbiAgICAgICAgMTEsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMjE5LFxuICAgICAgICA5M1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA4OCxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAxNjIsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAxNzEsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgMTU2LFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMTYyLFxuICAgICAgICAgIDEyMCxcbiAgICAgICAgICA3OSxcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDczLFxuICAgICAgICAgIDM1LFxuICAgICAgICAgIDY4LFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgMjI5LFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICAyMCxcbiAgICAgICAgICA2MixcbiAgICAgICAgICAxODksXG4gICAgICAgICAgMTMyLFxuICAgICAgICAgIDIwNyxcbiAgICAgICAgICAyMTAsXG4gICAgICAgICAgMjMsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMjM3LFxuICAgICAgICAgIDc3XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDEyLFxuICAgICAgICAgIDQ1LFxuICAgICAgICAgIDIyMSxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDE2OSxcbiAgICAgICAgICAyMDUsXG4gICAgICAgICAgNzYsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICAyMjcsXG4gICAgICAgICAgODMsXG4gICAgICAgICAgNTIsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAxNyxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAyMDksXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDU5LFxuICAgICAgICAgIDI1MyxcbiAgICAgICAgICAxMyxcbiAgICAgICAgICAxNzksXG4gICAgICAgICAgMTc0LFxuICAgICAgICAgIDEsXG4gICAgICAgICAgODIsXG4gICAgICAgICAgNDksXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDI1MixcbiAgICAgICAgICAyMDUsXG4gICAgICAgICAgNjBcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMzcsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMjM3LFxuICAgICAgICAyMDIsXG4gICAgICAgIDIwLFxuICAgICAgICAyLFxuICAgICAgICAxMTYsXG4gICAgICAgIDg4LFxuICAgICAgICAyMTQsXG4gICAgICAgIDEyMCxcbiAgICAgICAgNjMsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTUsXG4gICAgICAgIDIwNixcbiAgICAgICAgMjM3LFxuICAgICAgICAxMDcsXG4gICAgICAgIDY4LFxuICAgICAgICAyMjUsXG4gICAgICAgIDUzLFxuICAgICAgICAyMTIsXG4gICAgICAgIDE4MixcbiAgICAgICAgMzYsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTQyLFxuICAgICAgICA4NSxcbiAgICAgICAgMTc0LFxuICAgICAgICAxMDUsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTMsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMjEzLFxuICAgICAgICAyMTAsXG4gICAgICAgIDkzLFxuICAgICAgICAxMDksXG4gICAgICAgIDEyMCxcbiAgICAgICAgMjgsXG4gICAgICAgIDQ2LFxuICAgICAgICAxMSxcbiAgICAgICAgMjI2LFxuICAgICAgICA0NyxcbiAgICAgICAgNDUsXG4gICAgICAgIDE0OCxcbiAgICAgICAgNTksXG4gICAgICAgIDE4OCxcbiAgICAgICAgOTQsXG4gICAgICAgIDIyMyxcbiAgICAgICAgNjEsXG4gICAgICAgIDEyMixcbiAgICAgICAgNjIsXG4gICAgICAgIDE0LFxuICAgICAgICA5LFxuICAgICAgICAxMjQsXG4gICAgICAgIDE1LFxuICAgICAgICAxOSxcbiAgICAgICAgMjEsXG4gICAgICAgIDQ2LFxuICAgICAgICAyNTIsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjI2LFxuICAgICAgICAyNTEsXG4gICAgICAgIDk0LFxuICAgICAgICA1MCxcbiAgICAgICAgNixcbiAgICAgICAgMTM2XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxNjcsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiUkJ4RU9VY2syWmJpQzJwemRDZnlMQ2ZsTEEwNFE5MlgzQXROM2pHeTBQQT1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyNTY3NDkzODg2ODJAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkFDODVENzBBQjlDNjAwMUM5MTc0MEJFMERDNDcwRENBXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTc2OTg0MDg0M1xuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjI1Njc0OTM4ODY4MkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiQUNCRDlGMjQwMTkxQjdFNTM1RUYxMUNENDU0REJFMjdcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzY5ODQwODQzXG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiA2MSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiA2MSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIl9Ubm5ZZ1hlVHVPbnVRWENKYkc1aUFcIixcbiAgXCJwaG9uZUlkXCI6IFwiMDc1MjM2M2UtNGM2MS00MzVhLWJhZTgtYjE5M2Y2MDQ2M2M4XCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE5LFxuICAgICAgMTIyLFxuICAgICAgODUsXG4gICAgICA1NSxcbiAgICAgIDE0NCxcbiAgICAgIDI0OSxcbiAgICAgIDEzNCxcbiAgICAgIDYxLFxuICAgICAgMjUwLFxuICAgICAgMTI3LFxuICAgICAgNTUsXG4gICAgICAxNzMsXG4gICAgICA4MCxcbiAgICAgIDI0OCxcbiAgICAgIDIyMixcbiAgICAgIDg4LFxuICAgICAgMTY3LFxuICAgICAgOTIsXG4gICAgICAxMDcsXG4gICAgICA3MVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IGZhbHNlLFxuICBcImJhY2t1cFRva2VuXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTcwLFxuICAgICAgMTUsXG4gICAgICAyMDksXG4gICAgICAxMjUsXG4gICAgICAxNixcbiAgICAgIDIxNixcbiAgICAgIDUsXG4gICAgICAyMTAsXG4gICAgICA3OSxcbiAgICAgIDg3LFxuICAgICAgMTMwLFxuICAgICAgMjU1LFxuICAgICAgMTYsXG4gICAgICAxNSxcbiAgICAgIDE1LFxuICAgICAgMTQ5LFxuICAgICAgNDUsXG4gICAgICAxMTYsXG4gICAgICA0MyxcbiAgICAgIDIwMVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0tUQXl1VUVFTUhCOXNzR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiNFNmR0U1NmJEelBKVVM1dlZzVEUzckZUN2tpY0IySXhGZ2hzTUZ2NGpnZz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJtS0hmUWRjZHpXbTZPRWRWZ1dGQU1jVXV0YXY2SVF6ZGpBVWowS1NKK3dzdGpTcm9OZy9IdjY5S29vZHArdGR5L3pkcVhnMlQybFZ5R3Z6YUVMSFREQT09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCIrNm8xN3BYcjJWQlg5bmdOMmRzUDhkM2pid05rZFJINnpXUXF5eXNTNyt0QWt3ZG9pRmQyM1BHdWhZdzNYNjBuY256MVdQVHZ6aFE2ZFJpc2JCNDZoZz09XCJcbiAgfSxcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjI1Njc0OTM4ODY4Mjo0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCI4MDkyNDU2NjA3NzY2OjRAbGlkXCIsXG4gICAgXCJuYW1lXCI6IFwiMjgxNFwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjU2NzQ5Mzg4NjgyOjRAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyMjUsXG4gICAgICAgICAgMzksXG4gICAgICAgICAgMTk4LFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICAxNTUsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgNTEsXG4gICAgICAgICAgMjAxLFxuICAgICAgICAgIDgxLFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDExMSxcbiAgICAgICAgICA4NixcbiAgICAgICAgICAxOTYsXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDIyMixcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgODMsXG4gICAgICAgICAgMjM4LFxuICAgICAgICAgIDcyLFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICA3LFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDQ5LFxuICAgICAgICAgIDIyLFxuICAgICAgICAgIDgsXG4gICAgICAgICAgMTA4LFxuICAgICAgICAgIDQ4LFxuICAgICAgICAgIDkxLFxuICAgICAgICAgIDI0OCxcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgOFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzY5ODQwODM5LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBS0kvXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLSV9fLmpzb24iOiAie1wia2V5RGF0YVwiOlwiMEpjalQxZE9xcS9LZldmZGJrWExxRlVCMnJGckZ2RmN2Q3FUWkF3UGxQVT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjg2Nzc0ODIwLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3Njk4NDA4NDA3NTZcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
